apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: team-teamwork # CHANGE THIS! This will be the name of your application
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-dev
  env:
    - name: QUIZ_TOPIC
      value: leesah-quiz.leesah-rapid-v2